/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/screen.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";

export function Model({mouse, props}) {
    const { nodes, materials } = useGLTF('/models/screen.glb')
    const ref = useRef();
    useFrame(() => {
        if (!ref.current) return;

        ref.current.rotation.y +=
            (mouse.x * 0.45 - ref.current.rotation.y) * 0.06;

        ref.current.rotation.x +=
            (-mouse.y * 0.25 - ref.current.rotation.x) * 0.06;

        // subtle idle float
        ref.current.position.y =
            Math.sin(performance.now() * 0.001) * 0.015;
    });
    return (
      <group {...props} dispose={null}>
      <group position={[-0.121, -0.972, -0.043]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials.Glowbluestrong} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials.Base} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.002']} />
      </group>
      <group ref={ref}>
      <mesh geometry={nodes.InnerFrame.geometry} material={materials.SecondaryFrame} position={[-0.117, 0.387, -0.046]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.OuterFrame2.geometry} material={materials.OuterFrame} position={[1.662, 1.22, -0.029]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.OuterFrame1.geometry} material={materials.OuterFrame} position={[-1.914, 1.16, -0.021]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.SCreenBaseLarge.geometry} material={materials.Base} position={[-0.12, -0.687, -0.058]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.ScreenBase1.geometry} material={materials.Base} position={[-1.465, -0.625, -0.072]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.ScreenBase2.geometry} material={materials.Base} position={[1.313, -0.629, -0.013]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Strip1.geometry} material={materials.Glowblue} position={[-1.916, 1.474, 0.059]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Strip3.geometry} material={materials.Glowblue} position={[-1.934, -0.471, 0.059]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.PurpleLow.geometry} material={materials.Glowpurple} position={[-0.115, -0.625, 0.078]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.BlueUp.geometry} material={materials.Glowblue} position={[-0.113, 1.554, 0.108]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.LeftLightSmall.geometry} material={materials['orange neon']} position={[-2.021, 0.527, 0.065]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.RightLightSmall.geometry} material={materials['orange neon']} position={[1.781, 0.527, 0.065]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Strip2.geometry} material={materials.Glowblue} position={[1.694, 1.47, 0.059]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Strip4.geometry} material={materials.Glowblue} position={[1.697, -0.471, 0.059]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Button2.geometry} material={materials.Glowpurple} position={[1.407, -0.638, 0.001]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Button3.geometry} material={materials['orange neon']} position={[1.468, -0.638, 0.001]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Button1.geometry} material={materials.Glowblue} position={[1.348, -0.638, 0.001]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.GlassGlow.geometry} material={materials.GlassBorder} position={[-0.121, 0.505, -0.056]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Glass.geometry} material={materials.Material} position={[-0.121, 0.505, -0.056]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.ScreenContent.geometry} material={materials.ScreenContent} position={[-0.121, 0.505, -0.103]} rotation={[-Math.PI, 0, -Math.PI]} />
      </group>
      </group>
  )
}

export default Model;
useGLTF.preload("/models/screen.glb")
